version:  '3.3'
services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql1
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - dropbox
  nginx:
    image: nginx
    restart: on-failure
    container_name: nginx
    volumes:
      - '../:/usr/src/app'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8090:80'
    depends_on:
      - php
    networks:
      - dropbox
  php:
    container_name: php
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - '../:/usr/src/app'
      - './php/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
    restart: on-failure
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - DATABASE_URL=mysql://root:root@mysql:3306/dropbox?serverVersion=8.0.20
    depends_on:
      - mysql
    networks:
      - dropbox
networks:
  dropbox: